# Generated by Django 3.2.8 on 2021-10-21 01:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('key', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
