# Generated by Django 3.2.8 on 2021-10-21 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('path', models.FileField(null=True, upload_to='')),
                ('type', models.CharField(blank=True, choices=[('0', '비공개'), ('1', '공개'), ('2', '회의 참석자'), ('team1', '경영지원팀'), ('team2', 'it지원팀')], max_length=20, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meeting')),
            ],
        ),
    ]
