# Generated by Django 3.2.8 on 2021-10-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
